/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|


 * DO NOT EDIT THIS FILE!!
 *
 *  TO CUSTOMIZE itemOrdenBase PLEASE EDIT ../item-orden.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
import { Menu } from '../menu';
import { Ordenes } from '../ordenes';

/**
 * This is the model of itemOrden object
 *
 */
export class ItemOrdenBase {

    constructor() { }

    public _id: string;
    public cantidad?: string;
    public costo?: string;
    public fechaHora?: Date;
    public status?: number;
    // Relations idItemMenu
    public idItemMenu: Menu | string;
    // Relations idOrden
    public idOrden: Ordenes | string;
}
