/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|


 * DO NOT EDIT THIS FILE!!
 *
 *  TO CUSTOMIZE ordenesBase PLEASE EDIT ../ordenes.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
import { Mesas } from '../mesas';
import { Menu } from '../menu';
import { User } from '../user';

/**
 * This is the model of ordenes object
 *
 */
export class OrdenesBase {

    constructor() { }

    public _id: string;
    public fechaAbierto: Date;
    public fechaCerrado?: Date;
    public modoPago?: string;
    public status?: number;
    // Relations idMesa
    public idMesa: Mesas | string;
    // Relations idRestaurant
    public idRestaurant: Menu | string;
    // Relations idUsuario
    public idUsuario: User | string;
}
