/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE menuBaseService PLEASE EDIT ../menu.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Menu } from '../../domain/prueba-ska_db/menu';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../menu.service.ts
 */

/*
 * SCHEMA DB menu
 *
	{
		flag: {
			type: 'Boolean'
		},
		nombreMenu: {
			type: 'String'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		idEmpresa: {
			type: Schema.ObjectId,
			ref : "menu"
		},
		idItemMenu: {
			type: Schema.ObjectId,
			ref : "itemOrden"
		},
		idMenu: {
			type: Schema.ObjectId,
			ref : "categoriaMenu"
		},
		idMenu: {
			type: Schema.ObjectId,
			ref : "itemMenu"
		},
		idRestaurant: {
			type: Schema.ObjectId,
			ref : "ordenes"
		},
	}
 *
 */
@Injectable()
export class MenuBaseService {

    contextUrl: string = environment.endpoint + '/menu';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS


    // Custom APIs

}
